// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.polly.model



class DescribeVoicesResponse private constructor(builder: BuilderImpl) {
    /**
     * The pagination token to use in the next request to continue the
     * listing of voices. NextToken is returned only if the response
     * is truncated.
     */
    val nextToken: String? = builder.nextToken
    /**
     * A list of voices with their properties.
     */
    val voices: List<Voice>? = builder.voices

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DescribeVoicesResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeVoicesResponse(")
        append("nextToken=$nextToken,")
        append("voices=$voices)")
    }

    override fun hashCode(): kotlin.Int {
        var result = nextToken?.hashCode() ?: 0
        result = 31 * result + (voices?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DescribeVoicesResponse

        if (nextToken != other.nextToken) return false
        if (voices != other.voices) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DescribeVoicesResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DescribeVoicesResponse
        /**
         * The pagination token to use in the next request to continue the
         * listing of voices. NextToken is returned only if the response
         * is truncated.
         */
        fun nextToken(nextToken: String): FluentBuilder
        /**
         * A list of voices with their properties.
         */
        fun voices(voices: List<Voice>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The pagination token to use in the next request to continue the
         * listing of voices. NextToken is returned only if the response
         * is truncated.
         */
        var nextToken: String?
        /**
         * A list of voices with their properties.
         */
        var voices: List<Voice>?

        fun build(): DescribeVoicesResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var nextToken: String? = null
        override var voices: List<Voice>? = null

        constructor(x: DescribeVoicesResponse) : this() {
            this.nextToken = x.nextToken
            this.voices = x.voices
        }

        override fun build(): DescribeVoicesResponse = DescribeVoicesResponse(this)
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
        override fun voices(voices: List<Voice>): FluentBuilder = apply { this.voices = voices }
    }
}
