// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.polly.model



class GetSpeechSynthesisTaskRequest private constructor(builder: BuilderImpl) {
    /**
     * The Amazon Polly generated identifier for a speech synthesis task.
     */
    val taskId: String? = builder.taskId

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): GetSpeechSynthesisTaskRequest = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("GetSpeechSynthesisTaskRequest(")
        append("taskId=$taskId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = taskId?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as GetSpeechSynthesisTaskRequest

        if (taskId != other.taskId) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): GetSpeechSynthesisTaskRequest = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): GetSpeechSynthesisTaskRequest
        /**
         * The Amazon Polly generated identifier for a speech synthesis task.
         */
        fun taskId(taskId: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The Amazon Polly generated identifier for a speech synthesis task.
         */
        var taskId: String?

        fun build(): GetSpeechSynthesisTaskRequest
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var taskId: String? = null

        constructor(x: GetSpeechSynthesisTaskRequest) : this() {
            this.taskId = x.taskId
        }

        override fun build(): GetSpeechSynthesisTaskRequest = GetSpeechSynthesisTaskRequest(this)
        override fun taskId(taskId: String): FluentBuilder = apply { this.taskId = taskId }
    }
}
