// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class CreateInstanceEventWindowRequest private constructor(builder: BuilderImpl) {
    /**
     * The cron expression for the event window, for example, * 0-4,20-23 * * 1,5. If
     * you specify a cron expression, you can't specify a time range.
     * Constraints:
     * Only hour and day of the week values are supported.
     * For day of the week values, you can specify either integers 0 through
     * 6, or alternative single values SUN through
     * SAT.
     * The minute, month, and year must be specified by *.
     * The hour value must be one or a multiple range, for example, 0-4 or
     * 0-4,20-23.
     * Each hour range must be >= 2 hours, for example, 0-2 or
     * 20-23.
     * The event window must be >= 4 hours. The combined total time ranges in the event
     * window must be >= 4 hours.
     * For more information about cron expressions, see <a href="https://en.wikipedia.org/wiki/Cron">cron on the Wikipedia
     * website.
     */
    val cronExpression: String? = builder.cronExpression
    /**
     * Checks whether you have the required permissions for the action, without actually making the request,
     * and provides an error response. If you have the required permissions, the error response is DryRunOperation.
     * Otherwise, it is UnauthorizedOperation.
     */
    val dryRun: Boolean? = builder.dryRun
    /**
     * The name of the event window.
     */
    val name: String? = builder.name
    /**
     * The tags to apply to the event window.
     */
    val tagSpecifications: List<TagSpecification>? = builder.tagSpecifications
    /**
     * The time range for the event window. If you specify a time range, you can't specify a cron
     * expression.
     */
    val timeRanges: List<InstanceEventWindowTimeRangeRequest>? = builder.timeRanges

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): CreateInstanceEventWindowRequest = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("CreateInstanceEventWindowRequest(")
        append("cronExpression=$cronExpression,")
        append("dryRun=$dryRun,")
        append("name=$name,")
        append("tagSpecifications=$tagSpecifications,")
        append("timeRanges=$timeRanges)")
    }

    override fun hashCode(): kotlin.Int {
        var result = cronExpression?.hashCode() ?: 0
        result = 31 * result + (dryRun?.hashCode() ?: 0)
        result = 31 * result + (name?.hashCode() ?: 0)
        result = 31 * result + (tagSpecifications?.hashCode() ?: 0)
        result = 31 * result + (timeRanges?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CreateInstanceEventWindowRequest

        if (cronExpression != other.cronExpression) return false
        if (dryRun != other.dryRun) return false
        if (name != other.name) return false
        if (tagSpecifications != other.tagSpecifications) return false
        if (timeRanges != other.timeRanges) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): CreateInstanceEventWindowRequest = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): CreateInstanceEventWindowRequest
        /**
         * The cron expression for the event window, for example, * 0-4,20-23 * * 1,5. If
         * you specify a cron expression, you can't specify a time range.
         * Constraints:
         * Only hour and day of the week values are supported.
         * For day of the week values, you can specify either integers 0 through
         * 6, or alternative single values SUN through
         * SAT.
         * The minute, month, and year must be specified by *.
         * The hour value must be one or a multiple range, for example, 0-4 or
         * 0-4,20-23.
         * Each hour range must be >= 2 hours, for example, 0-2 or
         * 20-23.
         * The event window must be >= 4 hours. The combined total time ranges in the event
         * window must be >= 4 hours.
         * For more information about cron expressions, see <a href="https://en.wikipedia.org/wiki/Cron">cron on the Wikipedia
         * website.
         */
        fun cronExpression(cronExpression: String): FluentBuilder
        /**
         * Checks whether you have the required permissions for the action, without actually making the request,
         * and provides an error response. If you have the required permissions, the error response is DryRunOperation.
         * Otherwise, it is UnauthorizedOperation.
         */
        fun dryRun(dryRun: Boolean): FluentBuilder
        /**
         * The name of the event window.
         */
        fun name(name: String): FluentBuilder
        /**
         * The tags to apply to the event window.
         */
        fun tagSpecifications(tagSpecifications: List<TagSpecification>): FluentBuilder
        /**
         * The time range for the event window. If you specify a time range, you can't specify a cron
         * expression.
         */
        fun timeRanges(timeRanges: List<InstanceEventWindowTimeRangeRequest>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The cron expression for the event window, for example, * 0-4,20-23 * * 1,5. If
         * you specify a cron expression, you can't specify a time range.
         * Constraints:
         * Only hour and day of the week values are supported.
         * For day of the week values, you can specify either integers 0 through
         * 6, or alternative single values SUN through
         * SAT.
         * The minute, month, and year must be specified by *.
         * The hour value must be one or a multiple range, for example, 0-4 or
         * 0-4,20-23.
         * Each hour range must be >= 2 hours, for example, 0-2 or
         * 20-23.
         * The event window must be >= 4 hours. The combined total time ranges in the event
         * window must be >= 4 hours.
         * For more information about cron expressions, see <a href="https://en.wikipedia.org/wiki/Cron">cron on the Wikipedia
         * website.
         */
        var cronExpression: String?
        /**
         * Checks whether you have the required permissions for the action, without actually making the request,
         * and provides an error response. If you have the required permissions, the error response is DryRunOperation.
         * Otherwise, it is UnauthorizedOperation.
         */
        var dryRun: Boolean?
        /**
         * The name of the event window.
         */
        var name: String?
        /**
         * The tags to apply to the event window.
         */
        var tagSpecifications: List<TagSpecification>?
        /**
         * The time range for the event window. If you specify a time range, you can't specify a cron
         * expression.
         */
        var timeRanges: List<InstanceEventWindowTimeRangeRequest>?

        fun build(): CreateInstanceEventWindowRequest
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var cronExpression: String? = null
        override var dryRun: Boolean? = null
        override var name: String? = null
        override var tagSpecifications: List<TagSpecification>? = null
        override var timeRanges: List<InstanceEventWindowTimeRangeRequest>? = null

        constructor(x: CreateInstanceEventWindowRequest) : this() {
            this.cronExpression = x.cronExpression
            this.dryRun = x.dryRun
            this.name = x.name
            this.tagSpecifications = x.tagSpecifications
            this.timeRanges = x.timeRanges
        }

        override fun build(): CreateInstanceEventWindowRequest = CreateInstanceEventWindowRequest(this)
        override fun cronExpression(cronExpression: String): FluentBuilder = apply { this.cronExpression = cronExpression }
        override fun dryRun(dryRun: Boolean): FluentBuilder = apply { this.dryRun = dryRun }
        override fun name(name: String): FluentBuilder = apply { this.name = name }
        override fun tagSpecifications(tagSpecifications: List<TagSpecification>): FluentBuilder = apply { this.tagSpecifications = tagSpecifications }
        override fun timeRanges(timeRanges: List<InstanceEventWindowTimeRangeRequest>): FluentBuilder = apply { this.timeRanges = timeRanges }
    }
}
