// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class CreateLaunchTemplateVersionResponse private constructor(builder: BuilderImpl) {
    /**
     * Information about the launch template version.
     */
    val launchTemplateVersion: LaunchTemplateVersion? = builder.launchTemplateVersion
    /**
     * If the new version of the launch template contains parameters or parameter combinations that are not valid, an error code and an error message are returned for each issue that's found.
     */
    val warning: ValidationWarning? = builder.warning

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): CreateLaunchTemplateVersionResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("CreateLaunchTemplateVersionResponse(")
        append("launchTemplateVersion=$launchTemplateVersion,")
        append("warning=$warning)")
    }

    override fun hashCode(): kotlin.Int {
        var result = launchTemplateVersion?.hashCode() ?: 0
        result = 31 * result + (warning?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CreateLaunchTemplateVersionResponse

        if (launchTemplateVersion != other.launchTemplateVersion) return false
        if (warning != other.warning) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): CreateLaunchTemplateVersionResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): CreateLaunchTemplateVersionResponse
        /**
         * Information about the launch template version.
         */
        fun launchTemplateVersion(launchTemplateVersion: LaunchTemplateVersion): FluentBuilder
        /**
         * If the new version of the launch template contains parameters or parameter combinations that are not valid, an error code and an error message are returned for each issue that's found.
         */
        fun warning(warning: ValidationWarning): FluentBuilder
    }

    interface DslBuilder {
        /**
         * Information about the launch template version.
         */
        var launchTemplateVersion: LaunchTemplateVersion?
        /**
         * If the new version of the launch template contains parameters or parameter combinations that are not valid, an error code and an error message are returned for each issue that's found.
         */
        var warning: ValidationWarning?

        fun build(): CreateLaunchTemplateVersionResponse
        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.LaunchTemplateVersion] inside the given [block]
         */
        fun launchTemplateVersion(block: LaunchTemplateVersion.DslBuilder.() -> kotlin.Unit) {
            this.launchTemplateVersion = LaunchTemplateVersion.invoke(block)
        }
        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.ValidationWarning] inside the given [block]
         */
        fun warning(block: ValidationWarning.DslBuilder.() -> kotlin.Unit) {
            this.warning = ValidationWarning.invoke(block)
        }
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var launchTemplateVersion: LaunchTemplateVersion? = null
        override var warning: ValidationWarning? = null

        constructor(x: CreateLaunchTemplateVersionResponse) : this() {
            this.launchTemplateVersion = x.launchTemplateVersion
            this.warning = x.warning
        }

        override fun build(): CreateLaunchTemplateVersionResponse = CreateLaunchTemplateVersionResponse(this)
        override fun launchTemplateVersion(launchTemplateVersion: LaunchTemplateVersion): FluentBuilder = apply { this.launchTemplateVersion = launchTemplateVersion }
        override fun warning(warning: ValidationWarning): FluentBuilder = apply { this.warning = warning }
    }
}
