// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class DeleteFlowLogsResponse private constructor(builder: BuilderImpl) {
    /**
     * Information about the flow logs that could not be deleted successfully.
     */
    val unsuccessful: List<UnsuccessfulItem>? = builder.unsuccessful

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DeleteFlowLogsResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DeleteFlowLogsResponse(")
        append("unsuccessful=$unsuccessful)")
    }

    override fun hashCode(): kotlin.Int {
        var result = unsuccessful?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DeleteFlowLogsResponse

        if (unsuccessful != other.unsuccessful) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DeleteFlowLogsResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DeleteFlowLogsResponse
        /**
         * Information about the flow logs that could not be deleted successfully.
         */
        fun unsuccessful(unsuccessful: List<UnsuccessfulItem>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * Information about the flow logs that could not be deleted successfully.
         */
        var unsuccessful: List<UnsuccessfulItem>?

        fun build(): DeleteFlowLogsResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var unsuccessful: List<UnsuccessfulItem>? = null

        constructor(x: DeleteFlowLogsResponse) : this() {
            this.unsuccessful = x.unsuccessful
        }

        override fun build(): DeleteFlowLogsResponse = DeleteFlowLogsResponse(this)
        override fun unsuccessful(unsuccessful: List<UnsuccessfulItem>): FluentBuilder = apply { this.unsuccessful = unsuccessful }
    }
}
