// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Contains the parameters for DeleteCustomerGateway.
 */
class DeleteCustomerGatewayRequest private constructor(builder: BuilderImpl) {
    /**
     * The ID of the customer gateway.
     */
    val customerGatewayId: String? = builder.customerGatewayId
    /**
     * Checks whether you have the required permissions for the action, without actually
     * making the request, and provides an error response. If you have the required
     * permissions, the error response is DryRunOperation. Otherwise, it is
     * UnauthorizedOperation.
     */
    val dryRun: Boolean? = builder.dryRun

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DeleteCustomerGatewayRequest = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DeleteCustomerGatewayRequest(")
        append("customerGatewayId=$customerGatewayId,")
        append("dryRun=$dryRun)")
    }

    override fun hashCode(): kotlin.Int {
        var result = customerGatewayId?.hashCode() ?: 0
        result = 31 * result + (dryRun?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DeleteCustomerGatewayRequest

        if (customerGatewayId != other.customerGatewayId) return false
        if (dryRun != other.dryRun) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DeleteCustomerGatewayRequest = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DeleteCustomerGatewayRequest
        /**
         * The ID of the customer gateway.
         */
        fun customerGatewayId(customerGatewayId: String): FluentBuilder
        /**
         * Checks whether you have the required permissions for the action, without actually
         * making the request, and provides an error response. If you have the required
         * permissions, the error response is DryRunOperation. Otherwise, it is
         * UnauthorizedOperation.
         */
        fun dryRun(dryRun: Boolean): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The ID of the customer gateway.
         */
        var customerGatewayId: String?
        /**
         * Checks whether you have the required permissions for the action, without actually
         * making the request, and provides an error response. If you have the required
         * permissions, the error response is DryRunOperation. Otherwise, it is
         * UnauthorizedOperation.
         */
        var dryRun: Boolean?

        fun build(): DeleteCustomerGatewayRequest
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var customerGatewayId: String? = null
        override var dryRun: Boolean? = null

        constructor(x: DeleteCustomerGatewayRequest) : this() {
            this.customerGatewayId = x.customerGatewayId
            this.dryRun = x.dryRun
        }

        override fun build(): DeleteCustomerGatewayRequest = DeleteCustomerGatewayRequest(this)
        override fun customerGatewayId(customerGatewayId: String): FluentBuilder = apply { this.customerGatewayId = customerGatewayId }
        override fun dryRun(dryRun: Boolean): FluentBuilder = apply { this.dryRun = dryRun }
    }
}
