// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class DescribeClientVpnRoutesResponse private constructor(builder: BuilderImpl) {
    /**
     * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
     */
    val nextToken: String? = builder.nextToken
    /**
     * Information about the Client VPN endpoint routes.
     */
    val routes: List<ClientVpnRoute>? = builder.routes

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DescribeClientVpnRoutesResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeClientVpnRoutesResponse(")
        append("nextToken=$nextToken,")
        append("routes=$routes)")
    }

    override fun hashCode(): kotlin.Int {
        var result = nextToken?.hashCode() ?: 0
        result = 31 * result + (routes?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DescribeClientVpnRoutesResponse

        if (nextToken != other.nextToken) return false
        if (routes != other.routes) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DescribeClientVpnRoutesResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DescribeClientVpnRoutesResponse
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        fun nextToken(nextToken: String): FluentBuilder
        /**
         * Information about the Client VPN endpoint routes.
         */
        fun routes(routes: List<ClientVpnRoute>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        var nextToken: String?
        /**
         * Information about the Client VPN endpoint routes.
         */
        var routes: List<ClientVpnRoute>?

        fun build(): DescribeClientVpnRoutesResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var nextToken: String? = null
        override var routes: List<ClientVpnRoute>? = null

        constructor(x: DescribeClientVpnRoutesResponse) : this() {
            this.nextToken = x.nextToken
            this.routes = x.routes
        }

        override fun build(): DescribeClientVpnRoutesResponse = DescribeClientVpnRoutesResponse(this)
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
        override fun routes(routes: List<ClientVpnRoute>): FluentBuilder = apply { this.routes = routes }
    }
}
