// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class DescribeManagedPrefixListsResponse private constructor(builder: BuilderImpl) {
    /**
     * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
     */
    val nextToken: String? = builder.nextToken
    /**
     * Information about the prefix lists.
     */
    val prefixLists: List<ManagedPrefixList>? = builder.prefixLists

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DescribeManagedPrefixListsResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeManagedPrefixListsResponse(")
        append("nextToken=$nextToken,")
        append("prefixLists=$prefixLists)")
    }

    override fun hashCode(): kotlin.Int {
        var result = nextToken?.hashCode() ?: 0
        result = 31 * result + (prefixLists?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DescribeManagedPrefixListsResponse

        if (nextToken != other.nextToken) return false
        if (prefixLists != other.prefixLists) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DescribeManagedPrefixListsResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DescribeManagedPrefixListsResponse
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        fun nextToken(nextToken: String): FluentBuilder
        /**
         * Information about the prefix lists.
         */
        fun prefixLists(prefixLists: List<ManagedPrefixList>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        var nextToken: String?
        /**
         * Information about the prefix lists.
         */
        var prefixLists: List<ManagedPrefixList>?

        fun build(): DescribeManagedPrefixListsResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var nextToken: String? = null
        override var prefixLists: List<ManagedPrefixList>? = null

        constructor(x: DescribeManagedPrefixListsResponse) : this() {
            this.nextToken = x.nextToken
            this.prefixLists = x.prefixLists
        }

        override fun build(): DescribeManagedPrefixListsResponse = DescribeManagedPrefixListsResponse(this)
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
        override fun prefixLists(prefixLists: List<ManagedPrefixList>): FluentBuilder = apply { this.prefixLists = prefixLists }
    }
}
