// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class DescribeCoipPoolsResponse private constructor(builder: BuilderImpl) {
    /**
     * Information about the address pools.
     */
    val coipPools: List<CoipPool>? = builder.coipPools
    /**
     * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
     */
    val nextToken: String? = builder.nextToken

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DescribeCoipPoolsResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeCoipPoolsResponse(")
        append("coipPools=$coipPools,")
        append("nextToken=$nextToken)")
    }

    override fun hashCode(): kotlin.Int {
        var result = coipPools?.hashCode() ?: 0
        result = 31 * result + (nextToken?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DescribeCoipPoolsResponse

        if (coipPools != other.coipPools) return false
        if (nextToken != other.nextToken) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DescribeCoipPoolsResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DescribeCoipPoolsResponse
        /**
         * Information about the address pools.
         */
        fun coipPools(coipPools: List<CoipPool>): FluentBuilder
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        fun nextToken(nextToken: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * Information about the address pools.
         */
        var coipPools: List<CoipPool>?
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        var nextToken: String?

        fun build(): DescribeCoipPoolsResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var coipPools: List<CoipPool>? = null
        override var nextToken: String? = null

        constructor(x: DescribeCoipPoolsResponse) : this() {
            this.coipPools = x.coipPools
            this.nextToken = x.nextToken
        }

        override fun build(): DescribeCoipPoolsResponse = DescribeCoipPoolsResponse(this)
        override fun coipPools(coipPools: List<CoipPool>): FluentBuilder = apply { this.coipPools = coipPools }
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
    }
}
