// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class DescribeInstanceStatusResponse private constructor(builder: BuilderImpl) {
    /**
     * Information about the status of the instances.
     */
    val instanceStatuses: List<InstanceStatus>? = builder.instanceStatuses
    /**
     * The token to use to retrieve the next page of results. This value is null
     * when there are no more results to return.
     */
    val nextToken: String? = builder.nextToken

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DescribeInstanceStatusResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeInstanceStatusResponse(")
        append("instanceStatuses=$instanceStatuses,")
        append("nextToken=$nextToken)")
    }

    override fun hashCode(): kotlin.Int {
        var result = instanceStatuses?.hashCode() ?: 0
        result = 31 * result + (nextToken?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DescribeInstanceStatusResponse

        if (instanceStatuses != other.instanceStatuses) return false
        if (nextToken != other.nextToken) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DescribeInstanceStatusResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DescribeInstanceStatusResponse
        /**
         * Information about the status of the instances.
         */
        fun instanceStatuses(instanceStatuses: List<InstanceStatus>): FluentBuilder
        /**
         * The token to use to retrieve the next page of results. This value is null
         * when there are no more results to return.
         */
        fun nextToken(nextToken: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * Information about the status of the instances.
         */
        var instanceStatuses: List<InstanceStatus>?
        /**
         * The token to use to retrieve the next page of results. This value is null
         * when there are no more results to return.
         */
        var nextToken: String?

        fun build(): DescribeInstanceStatusResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var instanceStatuses: List<InstanceStatus>? = null
        override var nextToken: String? = null

        constructor(x: DescribeInstanceStatusResponse) : this() {
            this.instanceStatuses = x.instanceStatuses
            this.nextToken = x.nextToken
        }

        override fun build(): DescribeInstanceStatusResponse = DescribeInstanceStatusResponse(this)
        override fun instanceStatuses(instanceStatuses: List<InstanceStatus>): FluentBuilder = apply { this.instanceStatuses = instanceStatuses }
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
    }
}
