// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class DescribeVpcClassicLinkDnsSupportResponse private constructor(builder: BuilderImpl) {
    /**
     * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
     */
    val nextToken: String? = builder.nextToken
    /**
     * Information about the ClassicLink DNS support status of the VPCs.
     */
    val vpcs: List<ClassicLinkDnsSupport>? = builder.vpcs

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): DescribeVpcClassicLinkDnsSupportResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("DescribeVpcClassicLinkDnsSupportResponse(")
        append("nextToken=$nextToken,")
        append("vpcs=$vpcs)")
    }

    override fun hashCode(): kotlin.Int {
        var result = nextToken?.hashCode() ?: 0
        result = 31 * result + (vpcs?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as DescribeVpcClassicLinkDnsSupportResponse

        if (nextToken != other.nextToken) return false
        if (vpcs != other.vpcs) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): DescribeVpcClassicLinkDnsSupportResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): DescribeVpcClassicLinkDnsSupportResponse
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        fun nextToken(nextToken: String): FluentBuilder
        /**
         * Information about the ClassicLink DNS support status of the VPCs.
         */
        fun vpcs(vpcs: List<ClassicLinkDnsSupport>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        var nextToken: String?
        /**
         * Information about the ClassicLink DNS support status of the VPCs.
         */
        var vpcs: List<ClassicLinkDnsSupport>?

        fun build(): DescribeVpcClassicLinkDnsSupportResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var nextToken: String? = null
        override var vpcs: List<ClassicLinkDnsSupport>? = null

        constructor(x: DescribeVpcClassicLinkDnsSupportResponse) : this() {
            this.nextToken = x.nextToken
            this.vpcs = x.vpcs
        }

        override fun build(): DescribeVpcClassicLinkDnsSupportResponse = DescribeVpcClassicLinkDnsSupportResponse(this)
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
        override fun vpcs(vpcs: List<ClassicLinkDnsSupport>): FluentBuilder = apply { this.vpcs = vpcs }
    }
}
