// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes information used to set up an EBS volume specified in a block device
 * mapping.
 */
class EbsInstanceBlockDeviceSpecification private constructor(builder: BuilderImpl) {
    /**
     * Indicates whether the volume is deleted on instance termination.
     */
    val deleteOnTermination: Boolean? = builder.deleteOnTermination
    /**
     * The ID of the EBS volume.
     */
    val volumeId: String? = builder.volumeId

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): EbsInstanceBlockDeviceSpecification = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("EbsInstanceBlockDeviceSpecification(")
        append("deleteOnTermination=$deleteOnTermination,")
        append("volumeId=$volumeId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = deleteOnTermination?.hashCode() ?: 0
        result = 31 * result + (volumeId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as EbsInstanceBlockDeviceSpecification

        if (deleteOnTermination != other.deleteOnTermination) return false
        if (volumeId != other.volumeId) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): EbsInstanceBlockDeviceSpecification = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): EbsInstanceBlockDeviceSpecification
        /**
         * Indicates whether the volume is deleted on instance termination.
         */
        fun deleteOnTermination(deleteOnTermination: Boolean): FluentBuilder
        /**
         * The ID of the EBS volume.
         */
        fun volumeId(volumeId: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * Indicates whether the volume is deleted on instance termination.
         */
        var deleteOnTermination: Boolean?
        /**
         * The ID of the EBS volume.
         */
        var volumeId: String?

        fun build(): EbsInstanceBlockDeviceSpecification
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var deleteOnTermination: Boolean? = null
        override var volumeId: String? = null

        constructor(x: EbsInstanceBlockDeviceSpecification) : this() {
            this.deleteOnTermination = x.deleteOnTermination
            this.volumeId = x.volumeId
        }

        override fun build(): EbsInstanceBlockDeviceSpecification = EbsInstanceBlockDeviceSpecification(this)
        override fun deleteOnTermination(deleteOnTermination: Boolean): FluentBuilder = apply { this.deleteOnTermination = deleteOnTermination }
        override fun volumeId(volumeId: String): FluentBuilder = apply { this.volumeId = volumeId }
    }
}
