// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class EnableVolumeIoResponse private constructor(builder: BuilderImpl) {

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): EnableVolumeIoResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("EnableVolumeIoResponse(")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = javaClass.hashCode()
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as EnableVolumeIoResponse

        return true
    }

    interface FluentBuilder {
        fun build(): EnableVolumeIoResponse
    }

    interface DslBuilder {

        fun build(): EnableVolumeIoResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {

        constructor(x: EnableVolumeIoResponse) : this() {
        }

        override fun build(): EnableVolumeIoResponse = EnableVolumeIoResponse(this)
    }
}
