// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes a Reserved Instance whose queued purchase was not deleted.
 */
class FailedQueuedPurchaseDeletion private constructor(builder: BuilderImpl) {
    /**
     * The error.
     */
    val error: DeleteQueuedReservedInstancesError? = builder.error
    /**
     * The ID of the Reserved Instance.
     */
    val reservedInstancesId: String? = builder.reservedInstancesId

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): FailedQueuedPurchaseDeletion = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("FailedQueuedPurchaseDeletion(")
        append("error=$error,")
        append("reservedInstancesId=$reservedInstancesId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = error?.hashCode() ?: 0
        result = 31 * result + (reservedInstancesId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as FailedQueuedPurchaseDeletion

        if (error != other.error) return false
        if (reservedInstancesId != other.reservedInstancesId) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): FailedQueuedPurchaseDeletion = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): FailedQueuedPurchaseDeletion
        /**
         * The error.
         */
        fun error(error: DeleteQueuedReservedInstancesError): FluentBuilder
        /**
         * The ID of the Reserved Instance.
         */
        fun reservedInstancesId(reservedInstancesId: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The error.
         */
        var error: DeleteQueuedReservedInstancesError?
        /**
         * The ID of the Reserved Instance.
         */
        var reservedInstancesId: String?

        fun build(): FailedQueuedPurchaseDeletion
        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.DeleteQueuedReservedInstancesError] inside the given [block]
         */
        fun error(block: DeleteQueuedReservedInstancesError.DslBuilder.() -> kotlin.Unit) {
            this.error = DeleteQueuedReservedInstancesError.invoke(block)
        }
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var error: DeleteQueuedReservedInstancesError? = null
        override var reservedInstancesId: String? = null

        constructor(x: FailedQueuedPurchaseDeletion) : this() {
            this.error = x.error
            this.reservedInstancesId = x.reservedInstancesId
        }

        override fun build(): FailedQueuedPurchaseDeletion = FailedQueuedPurchaseDeletion(this)
        override fun error(error: DeleteQueuedReservedInstancesError): FluentBuilder = apply { this.error = error }
        override fun reservedInstancesId(reservedInstancesId: String): FluentBuilder = apply { this.reservedInstancesId = reservedInstancesId }
    }
}
