// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class GetTransitGatewayMulticastDomainAssociationsResponse private constructor(builder: BuilderImpl) {
    /**
     * Information about the multicast domain associations.
     */
    val multicastDomainAssociations: List<TransitGatewayMulticastDomainAssociation>? = builder.multicastDomainAssociations
    /**
     * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
     */
    val nextToken: String? = builder.nextToken

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): GetTransitGatewayMulticastDomainAssociationsResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("GetTransitGatewayMulticastDomainAssociationsResponse(")
        append("multicastDomainAssociations=$multicastDomainAssociations,")
        append("nextToken=$nextToken)")
    }

    override fun hashCode(): kotlin.Int {
        var result = multicastDomainAssociations?.hashCode() ?: 0
        result = 31 * result + (nextToken?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as GetTransitGatewayMulticastDomainAssociationsResponse

        if (multicastDomainAssociations != other.multicastDomainAssociations) return false
        if (nextToken != other.nextToken) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): GetTransitGatewayMulticastDomainAssociationsResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): GetTransitGatewayMulticastDomainAssociationsResponse
        /**
         * Information about the multicast domain associations.
         */
        fun multicastDomainAssociations(multicastDomainAssociations: List<TransitGatewayMulticastDomainAssociation>): FluentBuilder
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        fun nextToken(nextToken: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * Information about the multicast domain associations.
         */
        var multicastDomainAssociations: List<TransitGatewayMulticastDomainAssociation>?
        /**
         * The token to use to retrieve the next page of results. This value is null when there are no more results to return.
         */
        var nextToken: String?

        fun build(): GetTransitGatewayMulticastDomainAssociationsResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var multicastDomainAssociations: List<TransitGatewayMulticastDomainAssociation>? = null
        override var nextToken: String? = null

        constructor(x: GetTransitGatewayMulticastDomainAssociationsResponse) : this() {
            this.multicastDomainAssociations = x.multicastDomainAssociations
            this.nextToken = x.nextToken
        }

        override fun build(): GetTransitGatewayMulticastDomainAssociationsResponse = GetTransitGatewayMulticastDomainAssociationsResponse(this)
        override fun multicastDomainAssociations(multicastDomainAssociations: List<TransitGatewayMulticastDomainAssociation>): FluentBuilder = apply { this.multicastDomainAssociations = multicastDomainAssociations }
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
    }
}
