// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the IPv6 prefix.
 */
class Ipv6PrefixSpecification private constructor(builder: BuilderImpl) {
    /**
     * The IPv6 prefix.
     */
    val ipv6Prefix: String? = builder.ipv6Prefix

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): Ipv6PrefixSpecification = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("Ipv6PrefixSpecification(")
        append("ipv6Prefix=$ipv6Prefix)")
    }

    override fun hashCode(): kotlin.Int {
        var result = ipv6Prefix?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Ipv6PrefixSpecification

        if (ipv6Prefix != other.ipv6Prefix) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): Ipv6PrefixSpecification = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): Ipv6PrefixSpecification
        /**
         * The IPv6 prefix.
         */
        fun ipv6Prefix(ipv6Prefix: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The IPv6 prefix.
         */
        var ipv6Prefix: String?

        fun build(): Ipv6PrefixSpecification
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var ipv6Prefix: String? = null

        constructor(x: Ipv6PrefixSpecification) : this() {
            this.ipv6Prefix = x.ipv6Prefix
        }

        override fun build(): Ipv6PrefixSpecification = Ipv6PrefixSpecification(this)
        override fun ipv6Prefix(ipv6Prefix: String): FluentBuilder = apply { this.ipv6Prefix = ipv6Prefix }
    }
}
