// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes a launch permission modification.
 */
class LaunchPermissionModifications private constructor(builder: BuilderImpl) {
    /**
     * The Amazon Web Services account ID to add to the list of launch permissions for the AMI.
     */
    val add: List<LaunchPermission>? = builder.add
    /**
     * The Amazon Web Services account ID to remove from the list of launch permissions for the AMI.
     */
    val remove: List<LaunchPermission>? = builder.remove

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): LaunchPermissionModifications = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("LaunchPermissionModifications(")
        append("add=$add,")
        append("remove=$remove)")
    }

    override fun hashCode(): kotlin.Int {
        var result = add?.hashCode() ?: 0
        result = 31 * result + (remove?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as LaunchPermissionModifications

        if (add != other.add) return false
        if (remove != other.remove) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): LaunchPermissionModifications = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): LaunchPermissionModifications
        /**
         * The Amazon Web Services account ID to add to the list of launch permissions for the AMI.
         */
        fun add(add: List<LaunchPermission>): FluentBuilder
        /**
         * The Amazon Web Services account ID to remove from the list of launch permissions for the AMI.
         */
        fun remove(remove: List<LaunchPermission>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The Amazon Web Services account ID to add to the list of launch permissions for the AMI.
         */
        var add: List<LaunchPermission>?
        /**
         * The Amazon Web Services account ID to remove from the list of launch permissions for the AMI.
         */
        var remove: List<LaunchPermission>?

        fun build(): LaunchPermissionModifications
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var add: List<LaunchPermission>? = null
        override var remove: List<LaunchPermission>? = null

        constructor(x: LaunchPermissionModifications) : this() {
            this.add = x.add
            this.remove = x.remove
        }

        override fun build(): LaunchPermissionModifications = LaunchPermissionModifications(this)
        override fun add(add: List<LaunchPermission>): FluentBuilder = apply { this.add = add }
        override fun remove(remove: List<LaunchPermission>): FluentBuilder = apply { this.remove = remove }
    }
}
