// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Contains the output of PurchaseReservedInstancesOffering.
 */
class PurchaseReservedInstancesOfferingResponse private constructor(builder: BuilderImpl) {
    /**
     * The IDs of the purchased Reserved Instances. If your purchase crosses into a discounted
     * pricing tier, the final Reserved Instances IDs might change. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts-reserved-instances-application.html#crossing-pricing-tiers">Crossing
     * pricing tiers in the Amazon Elastic Compute Cloud User Guide.
     */
    val reservedInstancesId: String? = builder.reservedInstancesId

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): PurchaseReservedInstancesOfferingResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("PurchaseReservedInstancesOfferingResponse(")
        append("reservedInstancesId=$reservedInstancesId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = reservedInstancesId?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as PurchaseReservedInstancesOfferingResponse

        if (reservedInstancesId != other.reservedInstancesId) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): PurchaseReservedInstancesOfferingResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): PurchaseReservedInstancesOfferingResponse
        /**
         * The IDs of the purchased Reserved Instances. If your purchase crosses into a discounted
         * pricing tier, the final Reserved Instances IDs might change. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts-reserved-instances-application.html#crossing-pricing-tiers">Crossing
         * pricing tiers in the Amazon Elastic Compute Cloud User Guide.
         */
        fun reservedInstancesId(reservedInstancesId: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The IDs of the purchased Reserved Instances. If your purchase crosses into a discounted
         * pricing tier, the final Reserved Instances IDs might change. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts-reserved-instances-application.html#crossing-pricing-tiers">Crossing
         * pricing tiers in the Amazon Elastic Compute Cloud User Guide.
         */
        var reservedInstancesId: String?

        fun build(): PurchaseReservedInstancesOfferingResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var reservedInstancesId: String? = null

        constructor(x: PurchaseReservedInstancesOfferingResponse) : this() {
            this.reservedInstancesId = x.reservedInstancesId
        }

        override fun build(): PurchaseReservedInstancesOfferingResponse = PurchaseReservedInstancesOfferingResponse(this)
        override fun reservedInstancesId(reservedInstancesId: String): FluentBuilder = apply { this.reservedInstancesId = reservedInstancesId }
    }
}
