// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class ReleaseHostsRequest private constructor(builder: BuilderImpl) {
    /**
     * The IDs of the Dedicated Hosts to release.
     */
    val hostIds: List<String>? = builder.hostIds

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): ReleaseHostsRequest = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("ReleaseHostsRequest(")
        append("hostIds=$hostIds)")
    }

    override fun hashCode(): kotlin.Int {
        var result = hostIds?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ReleaseHostsRequest

        if (hostIds != other.hostIds) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): ReleaseHostsRequest = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): ReleaseHostsRequest
        /**
         * The IDs of the Dedicated Hosts to release.
         */
        fun hostIds(hostIds: List<String>): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The IDs of the Dedicated Hosts to release.
         */
        var hostIds: List<String>?

        fun build(): ReleaseHostsRequest
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var hostIds: List<String>? = null

        constructor(x: ReleaseHostsRequest) : this() {
            this.hostIds = x.hostIds
        }

        override fun build(): ReleaseHostsRequest = ReleaseHostsRequest(this)
        override fun hostIds(hostIds: List<String>): FluentBuilder = apply { this.hostIds = hostIds }
    }
}
