// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes a Spot Instance state change.
 */
class SpotInstanceStateFault private constructor(builder: BuilderImpl) {
    /**
     * The reason code for the Spot Instance state change.
     */
    val code: String? = builder.code
    /**
     * The message for the Spot Instance state change.
     */
    val message: String? = builder.message

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): SpotInstanceStateFault = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("SpotInstanceStateFault(")
        append("code=$code,")
        append("message=$message)")
    }

    override fun hashCode(): kotlin.Int {
        var result = code?.hashCode() ?: 0
        result = 31 * result + (message?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SpotInstanceStateFault

        if (code != other.code) return false
        if (message != other.message) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): SpotInstanceStateFault = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): SpotInstanceStateFault
        /**
         * The reason code for the Spot Instance state change.
         */
        fun code(code: String): FluentBuilder
        /**
         * The message for the Spot Instance state change.
         */
        fun message(message: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The reason code for the Spot Instance state change.
         */
        var code: String?
        /**
         * The message for the Spot Instance state change.
         */
        var message: String?

        fun build(): SpotInstanceStateFault
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var code: String? = null
        override var message: String? = null

        constructor(x: SpotInstanceStateFault) : this() {
            this.code = x.code
            this.message = x.message
        }

        override fun build(): SpotInstanceStateFault = SpotInstanceStateFault(this)
        override fun code(code: String): FluentBuilder = apply { this.code = code }
        override fun message(message: String): FluentBuilder = apply { this.message = message }
    }
}
