// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the burstable performance instance whose credit option for CPU usage was not
 * modified.
 */
class UnsuccessfulInstanceCreditSpecificationItem private constructor(builder: BuilderImpl) {
    /**
     * The applicable error for the burstable performance instance whose credit option for
     * CPU usage was not modified.
     */
    val error: UnsuccessfulInstanceCreditSpecificationItemError? = builder.error
    /**
     * The ID of the instance.
     */
    val instanceId: String? = builder.instanceId

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): UnsuccessfulInstanceCreditSpecificationItem = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("UnsuccessfulInstanceCreditSpecificationItem(")
        append("error=$error,")
        append("instanceId=$instanceId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = error?.hashCode() ?: 0
        result = 31 * result + (instanceId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as UnsuccessfulInstanceCreditSpecificationItem

        if (error != other.error) return false
        if (instanceId != other.instanceId) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): UnsuccessfulInstanceCreditSpecificationItem = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): UnsuccessfulInstanceCreditSpecificationItem
        /**
         * The applicable error for the burstable performance instance whose credit option for
         * CPU usage was not modified.
         */
        fun error(error: UnsuccessfulInstanceCreditSpecificationItemError): FluentBuilder
        /**
         * The ID of the instance.
         */
        fun instanceId(instanceId: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The applicable error for the burstable performance instance whose credit option for
         * CPU usage was not modified.
         */
        var error: UnsuccessfulInstanceCreditSpecificationItemError?
        /**
         * The ID of the instance.
         */
        var instanceId: String?

        fun build(): UnsuccessfulInstanceCreditSpecificationItem
        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.UnsuccessfulInstanceCreditSpecificationItemError] inside the given [block]
         */
        fun error(block: UnsuccessfulInstanceCreditSpecificationItemError.DslBuilder.() -> kotlin.Unit) {
            this.error = UnsuccessfulInstanceCreditSpecificationItemError.invoke(block)
        }
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var error: UnsuccessfulInstanceCreditSpecificationItemError? = null
        override var instanceId: String? = null

        constructor(x: UnsuccessfulInstanceCreditSpecificationItem) : this() {
            this.error = x.error
            this.instanceId = x.instanceId
        }

        override fun build(): UnsuccessfulInstanceCreditSpecificationItem = UnsuccessfulInstanceCreditSpecificationItem(this)
        override fun error(error: UnsuccessfulInstanceCreditSpecificationItemError): FluentBuilder = apply { this.error = error }
        override fun instanceId(instanceId: String): FluentBuilder = apply { this.instanceId = instanceId }
    }
}
