// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.sts.model

import aws.smithy.kotlin.runtime.ServiceErrorMetadata

/**
 * The web identity token that was passed could not be validated by Amazon Web Services. Get a new
 * identity token from the identity provider and then retry the request.
 */
class InvalidIdentityTokenException private constructor(builder: BuilderImpl) : StsException() {

    override val message: String? = builder.message

    init {
        sdkErrorMetadata.attributes[ServiceErrorMetadata.ErrorType] = ErrorType.Client
    }

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): InvalidIdentityTokenException = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("InvalidIdentityTokenException(")
        append("message=$message)")
    }

    override fun hashCode(): kotlin.Int {
        var result = message?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as InvalidIdentityTokenException

        if (message != other.message) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): InvalidIdentityTokenException = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): InvalidIdentityTokenException
        fun message(message: String): FluentBuilder
    }

    interface DslBuilder {
        var message: String?

        fun build(): InvalidIdentityTokenException
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var message: String? = null

        constructor(x: InvalidIdentityTokenException) : this() {
            this.message = x.message
        }

        override fun build(): InvalidIdentityTokenException = InvalidIdentityTokenException(this)
        override fun message(message: String): FluentBuilder = apply { this.message = message }
    }
}
