// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.dynamodb.model



class ListExportsResponse private constructor(builder: BuilderImpl) {
    /**
     * A list of ExportSummary objects.
     */
    val exportSummaries: List<ExportSummary>? = builder.exportSummaries
    /**
     * If this value is returned, there are additional results to be displayed. To retrieve
     * them, call ListExports again, with NextToken set to this
     * value.
     */
    val nextToken: String? = builder.nextToken

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): ListExportsResponse = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("ListExportsResponse(")
        append("exportSummaries=$exportSummaries,")
        append("nextToken=$nextToken)")
    }

    override fun hashCode(): kotlin.Int {
        var result = exportSummaries?.hashCode() ?: 0
        result = 31 * result + (nextToken?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ListExportsResponse

        if (exportSummaries != other.exportSummaries) return false
        if (nextToken != other.nextToken) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): ListExportsResponse = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): ListExportsResponse
        /**
         * A list of ExportSummary objects.
         */
        fun exportSummaries(exportSummaries: List<ExportSummary>): FluentBuilder
        /**
         * If this value is returned, there are additional results to be displayed. To retrieve
         * them, call ListExports again, with NextToken set to this
         * value.
         */
        fun nextToken(nextToken: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * A list of ExportSummary objects.
         */
        var exportSummaries: List<ExportSummary>?
        /**
         * If this value is returned, there are additional results to be displayed. To retrieve
         * them, call ListExports again, with NextToken set to this
         * value.
         */
        var nextToken: String?

        fun build(): ListExportsResponse
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var exportSummaries: List<ExportSummary>? = null
        override var nextToken: String? = null

        constructor(x: ListExportsResponse) : this() {
            this.exportSummaries = x.exportSummaries
            this.nextToken = x.nextToken
        }

        override fun build(): ListExportsResponse = ListExportsResponse(this)
        override fun exportSummaries(exportSummaries: List<ExportSummary>): FluentBuilder = apply { this.exportSummaries = exportSummaries }
        override fun nextToken(nextToken: String): FluentBuilder = apply { this.nextToken = nextToken }
    }
}
