// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.s3.model



/**
 * Contains information about where to publish the analytics results.
 */
class AnalyticsS3BucketDestination private constructor(builder: BuilderImpl) {
    /**
     * The Amazon Resource Name (ARN) of the bucket to which data is exported.
     */
    val bucket: String? = builder.bucket
    /**
     * The account ID that owns the destination S3 bucket. If no account ID is provided, the
     * owner is not validated before exporting data.
     * Although this value is optional, we strongly recommend that you set it to help
     * prevent problems if the destination bucket ownership changes.
     */
    val bucketAccountId: String? = builder.bucketAccountId
    /**
     * Specifies the file format used when exporting data to Amazon S3.
     */
    val format: AnalyticsS3ExportFileFormat? = builder.format
    /**
     * The prefix to use when exporting data. The prefix is prepended to all results.
     */
    val prefix: String? = builder.prefix

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): AnalyticsS3BucketDestination = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("AnalyticsS3BucketDestination(")
        append("bucket=$bucket,")
        append("bucketAccountId=$bucketAccountId,")
        append("format=$format,")
        append("prefix=$prefix)")
    }

    override fun hashCode(): kotlin.Int {
        var result = bucket?.hashCode() ?: 0
        result = 31 * result + (bucketAccountId?.hashCode() ?: 0)
        result = 31 * result + (format?.hashCode() ?: 0)
        result = 31 * result + (prefix?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as AnalyticsS3BucketDestination

        if (bucket != other.bucket) return false
        if (bucketAccountId != other.bucketAccountId) return false
        if (format != other.format) return false
        if (prefix != other.prefix) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): AnalyticsS3BucketDestination = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): AnalyticsS3BucketDestination
        /**
         * The Amazon Resource Name (ARN) of the bucket to which data is exported.
         */
        fun bucket(bucket: String): FluentBuilder
        /**
         * The account ID that owns the destination S3 bucket. If no account ID is provided, the
         * owner is not validated before exporting data.
         * Although this value is optional, we strongly recommend that you set it to help
         * prevent problems if the destination bucket ownership changes.
         */
        fun bucketAccountId(bucketAccountId: String): FluentBuilder
        /**
         * Specifies the file format used when exporting data to Amazon S3.
         */
        fun format(format: AnalyticsS3ExportFileFormat): FluentBuilder
        /**
         * The prefix to use when exporting data. The prefix is prepended to all results.
         */
        fun prefix(prefix: String): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The Amazon Resource Name (ARN) of the bucket to which data is exported.
         */
        var bucket: String?
        /**
         * The account ID that owns the destination S3 bucket. If no account ID is provided, the
         * owner is not validated before exporting data.
         * Although this value is optional, we strongly recommend that you set it to help
         * prevent problems if the destination bucket ownership changes.
         */
        var bucketAccountId: String?
        /**
         * Specifies the file format used when exporting data to Amazon S3.
         */
        var format: AnalyticsS3ExportFileFormat?
        /**
         * The prefix to use when exporting data. The prefix is prepended to all results.
         */
        var prefix: String?

        fun build(): AnalyticsS3BucketDestination
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var bucket: String? = null
        override var bucketAccountId: String? = null
        override var format: AnalyticsS3ExportFileFormat? = null
        override var prefix: String? = null

        constructor(x: AnalyticsS3BucketDestination) : this() {
            this.bucket = x.bucket
            this.bucketAccountId = x.bucketAccountId
            this.format = x.format
            this.prefix = x.prefix
        }

        override fun build(): AnalyticsS3BucketDestination = AnalyticsS3BucketDestination(this)
        override fun bucket(bucket: String): FluentBuilder = apply { this.bucket = bucket }
        override fun bucketAccountId(bucketAccountId: String): FluentBuilder = apply { this.bucketAccountId = bucketAccountId }
        override fun format(format: AnalyticsS3ExportFileFormat): FluentBuilder = apply { this.format = format }
        override fun prefix(prefix: String): FluentBuilder = apply { this.prefix = prefix }
    }
}
