// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.s3.model



/**
 * Specifies the configuration and any analyses for the analytics filter of an Amazon S3 bucket.
 */
class AnalyticsConfiguration private constructor(builder: BuilderImpl) {
    /**
     * The filter used to describe a set of objects for analyses. A filter must have exactly
     * one prefix, one tag, or one conjunction (AnalyticsAndOperator). If no filter is provided,
     * all objects will be considered in any analysis.
     */
    val filter: AnalyticsFilter? = builder.filter
    /**
     * The ID that identifies the analytics configuration.
     */
    val id: String? = builder.id
    /**
     * Contains data related to access patterns to be collected and made available to analyze
     * the tradeoffs between different storage classes.
     */
    val storageClassAnalysis: StorageClassAnalysis? = builder.storageClassAnalysis

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): AnalyticsConfiguration = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("AnalyticsConfiguration(")
        append("filter=$filter,")
        append("id=$id,")
        append("storageClassAnalysis=$storageClassAnalysis)")
    }

    override fun hashCode(): kotlin.Int {
        var result = filter?.hashCode() ?: 0
        result = 31 * result + (id?.hashCode() ?: 0)
        result = 31 * result + (storageClassAnalysis?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as AnalyticsConfiguration

        if (filter != other.filter) return false
        if (id != other.id) return false
        if (storageClassAnalysis != other.storageClassAnalysis) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): AnalyticsConfiguration = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): AnalyticsConfiguration
        /**
         * The filter used to describe a set of objects for analyses. A filter must have exactly
         * one prefix, one tag, or one conjunction (AnalyticsAndOperator). If no filter is provided,
         * all objects will be considered in any analysis.
         */
        fun filter(filter: AnalyticsFilter): FluentBuilder
        /**
         * The ID that identifies the analytics configuration.
         */
        fun id(id: String): FluentBuilder
        /**
         * Contains data related to access patterns to be collected and made available to analyze
         * the tradeoffs between different storage classes.
         */
        fun storageClassAnalysis(storageClassAnalysis: StorageClassAnalysis): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The filter used to describe a set of objects for analyses. A filter must have exactly
         * one prefix, one tag, or one conjunction (AnalyticsAndOperator). If no filter is provided,
         * all objects will be considered in any analysis.
         */
        var filter: AnalyticsFilter?
        /**
         * The ID that identifies the analytics configuration.
         */
        var id: String?
        /**
         * Contains data related to access patterns to be collected and made available to analyze
         * the tradeoffs between different storage classes.
         */
        var storageClassAnalysis: StorageClassAnalysis?

        fun build(): AnalyticsConfiguration
        /**
         * construct an [aws.sdk.kotlin.services.s3.model.StorageClassAnalysis] inside the given [block]
         */
        fun storageClassAnalysis(block: StorageClassAnalysis.DslBuilder.() -> kotlin.Unit) {
            this.storageClassAnalysis = StorageClassAnalysis.invoke(block)
        }
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var filter: AnalyticsFilter? = null
        override var id: String? = null
        override var storageClassAnalysis: StorageClassAnalysis? = null

        constructor(x: AnalyticsConfiguration) : this() {
            this.filter = x.filter
            this.id = x.id
            this.storageClassAnalysis = x.storageClassAnalysis
        }

        override fun build(): AnalyticsConfiguration = AnalyticsConfiguration(this)
        override fun filter(filter: AnalyticsFilter): FluentBuilder = apply { this.filter = filter }
        override fun id(id: String): FluentBuilder = apply { this.id = id }
        override fun storageClassAnalysis(storageClassAnalysis: StorageClassAnalysis): FluentBuilder = apply { this.storageClassAnalysis = storageClassAnalysis }
    }
}
