// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.s3.model



/**
 * This data type contains information about progress of an operation.
 */
class Progress private constructor(builder: BuilderImpl) {
    /**
     * The current number of uncompressed object bytes processed.
     */
    val bytesProcessed: Long = builder.bytesProcessed
    /**
     * The current number of bytes of records payload data returned.
     */
    val bytesReturned: Long = builder.bytesReturned
    /**
     * The current number of object bytes scanned.
     */
    val bytesScanned: Long = builder.bytesScanned

    companion object {
        @JvmStatic
        fun fluentBuilder(): FluentBuilder = BuilderImpl()

        internal fun builder(): DslBuilder = BuilderImpl()

        operator fun invoke(block: DslBuilder.() -> kotlin.Unit): Progress = BuilderImpl().apply(block).build()

    }

    override fun toString(): kotlin.String = buildString {
        append("Progress(")
        append("bytesProcessed=$bytesProcessed,")
        append("bytesReturned=$bytesReturned,")
        append("bytesScanned=$bytesScanned)")
    }

    override fun hashCode(): kotlin.Int {
        var result = bytesProcessed.hashCode()
        result = 31 * result + (bytesReturned.hashCode())
        result = 31 * result + (bytesScanned.hashCode())
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Progress

        if (bytesProcessed != other.bytesProcessed) return false
        if (bytesReturned != other.bytesReturned) return false
        if (bytesScanned != other.bytesScanned) return false

        return true
    }

    fun copy(block: DslBuilder.() -> kotlin.Unit = {}): Progress = BuilderImpl(this).apply(block).build()

    interface FluentBuilder {
        fun build(): Progress
        /**
         * The current number of uncompressed object bytes processed.
         */
        fun bytesProcessed(bytesProcessed: Long): FluentBuilder
        /**
         * The current number of bytes of records payload data returned.
         */
        fun bytesReturned(bytesReturned: Long): FluentBuilder
        /**
         * The current number of object bytes scanned.
         */
        fun bytesScanned(bytesScanned: Long): FluentBuilder
    }

    interface DslBuilder {
        /**
         * The current number of uncompressed object bytes processed.
         */
        var bytesProcessed: Long
        /**
         * The current number of bytes of records payload data returned.
         */
        var bytesReturned: Long
        /**
         * The current number of object bytes scanned.
         */
        var bytesScanned: Long

        fun build(): Progress
    }

    private class BuilderImpl() : FluentBuilder, DslBuilder {
        override var bytesProcessed: Long = 0L
        override var bytesReturned: Long = 0L
        override var bytesScanned: Long = 0L

        constructor(x: Progress) : this() {
            this.bytesProcessed = x.bytesProcessed
            this.bytesReturned = x.bytesReturned
            this.bytesScanned = x.bytesScanned
        }

        override fun build(): Progress = Progress(this)
        override fun bytesProcessed(bytesProcessed: Long): FluentBuilder = apply { this.bytesProcessed = bytesProcessed }
        override fun bytesReturned(bytesReturned: Long): FluentBuilder = apply { this.bytesReturned = bytesReturned }
        override fun bytesScanned(bytesScanned: Long): FluentBuilder = apply { this.bytesScanned = bytesScanned }
    }
}
